# Generated by Django 5.2.6 on 2025-09-19 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=24)),
                ('change_24h_percent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('market_cap_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('volume_24h_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('total_supply', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('ath', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('atl', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='crypto.cryptoasset')),
            ],
            options={
                'get_latest_by': 'last_updated',
                'indexes': [models.Index(fields=['asset', 'last_updated'], name='crypto_cryp_asset_i_957490_idx')],
            },
        ),
    ]
